name: Working with secrets in Github Actions

on:
    push:
        branches:
        - main

jobs:
      build:
        runs-on: ubuntu-latest
        steps:
          - name: Print the secret
          run: echo ${{ secrets.GREETING }}


